version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Install
          command: |
            npm install
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Deploy
          command: |
            npm run deploy